# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 19:26
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Aivailibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DateTimeField()),
                ('closing', models.DateTimeField()),
                ('notAvailableFrom', models.DateTimeField()),
                ('notAvailableTill', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='ProfileUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sportcenterName', models.CharField(default='', max_length=100)),
                ('password', models.CharField(default='', max_length=70)),
                ('role', models.CharField(max_length=255)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TerrainType', models.CharField(max_length=255)),
                ('minimumCapacity', models.IntegerField(default=0)),
                ('maximumCapacity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('photo', models.FileField(upload_to='')),
                ('terrainAvailibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Terrain',
            },
        ),
        migrations.AddField(
            model_name='aivailibility',
            name='availibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Terrain'),
        ),
    ]
