# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 00:57
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20180725_1650'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DateTimeField(default='')),
                ('closing', models.DateTimeField()),
                ('notAvailableFrom', models.DateTimeField()),
                ('notAvailableTill', models.DateTimeField()),
                ('TerrainType', models.CharField(max_length=255)),
                ('minimumCapacity', models.IntegerField(default=0)),
                ('maximumCapacity', models.IntegerField(default=0)),
                ('Price', models.IntegerField(default=0)),
                ('terrainAvailibility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='Price',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='TerrainType',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='maximumCapacity',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='minimumCapacity',
        ),
    ]
