# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 03:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20180725_2057'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='terrain',
            options={'verbose_name_plural': 'Terrain'},
        ),
    ]
