# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-26 06:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180725_2334'),
    ]

    operations = [
        migrations.CreateModel(
            name='Aivailibility',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opening', models.DateTimeField(default='')),
                ('closing', models.DateTimeField()),
                ('notAvailableFrom', models.DateTimeField()),
                ('notAvailableTill', models.DateTimeField()),
            ],
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='closing',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='notAvailableFrom',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='notAvailableTill',
        ),
        migrations.RemoveField(
            model_name='terrain',
            name='opening',
        ),
        migrations.AddField(
            model_name='aivailibility',
            name='availibility',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Terrain'),
        ),
    ]
