# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 21:49
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20180726_0219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profileuser',
            options={},
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='terrainAvailibility',
        ),
        migrations.AddField(
            model_name='profileuser',
            name='password',
            field=models.CharField(default='', max_length=70),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='role',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='sportcenterName',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='terrain',
            name='photo',
            field=models.FileField(null=True, upload_to='documents/'),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='opening',
            field=models.DateTimeField(),
        ),
    ]
