# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 22:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_profileuser_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='photo',
            field=models.FileField(null=True, upload_to='user_directory_path'),
        ),
    ]
