# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20180727_1811'),
    ]

    operations = [
        migrations.AddField(
            model_name='terrain',
            name='path',
            field=models.CharField(default='user_directory_path', max_length=255),
        ),
    ]
