# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 22:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_terrain_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='photo',
            field=models.FileField(blank=True, default='', upload_to='user_directory_path'),
        ),
    ]
