# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-27 23:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20180727_1850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terrain',
            name='photo',
            field=models.ImageField(default='', upload_to='user_directory_path'),
        ),
    ]
