# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-30 15:39
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_aivailibility_partner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aivailibility',
            name='partner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
