# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_remove_aivailibility_partner'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='photo',
            field=models.ImageField(default='', upload_to='user_directory_path'),
        ),
    ]
