# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180731_1956'),
    ]

    operations = [
        migrations.AddField(
            model_name='aivailibility',
            name='dayAvailibility',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='closing',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='notAvailableFrom',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='notAvailableTill',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='opening',
            field=models.TimeField(),
        ),
    ]
