# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 20:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180801_1816'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aivailibility',
            name='dayAvailibility',
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='closing',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='notAvailableFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='notAvailableTill',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='aivailibility',
            name='opening',
            field=models.DateTimeField(null=True),
        ),
    ]
