# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180802_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aivailibility',
            options={'verbose_name_plural': 'Aivailibility'},
        ),
    ]
