# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_terrain_sportcentername'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profileuser',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='profileuser',
            name='sportcenterName',
        ),
        migrations.AlterField(
            model_name='profileuser',
            name='role',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
