# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 13:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20180813_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='phone',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='profileuser',
            name='postalcode',
            field=models.CharField(max_length=6, null=True),
        ),
    ]
