# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-20 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0025_auto_20180820_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='membership',
            name='membershipNumber',
            field=models.CharField(default='', max_length=255),
        ),
    ]
