# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 01:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0026_membership_membershipnumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membershipNumber',
            field=models.CharField(default='', max_length=255, null=True),
        ),
    ]
