# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 01:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_auto_20180820_2117'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='membership',
            name='terrain',
        ),
    ]
