# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 03:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_auto_20180820_2132'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='membership',
            options={'verbose_name_plural': 'Membership'},
        ),
    ]
