# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 03:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_auto_20180820_2309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
