# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 15:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_auto_20180820_2327'),
    ]

    operations = [
        migrations.AddField(
            model_name='profileuser',
            name='photo',
            field=models.ImageField(default='', upload_to='user_directory_path'),
        ),
    ]
