# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 22:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_profileuser_path'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='photo',
            field=models.ImageField(default='', upload_to='user_profile_path'),
        ),
    ]
