# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-21 23:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180821_1834'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profileuser',
            name='path',
            field=models.CharField(default='user_profile_path', max_length=255),
        ),
    ]
