# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-07-31 23:56
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('7917558d-119f-4e19-a5bd-e2a5875e228d'), max_length=254),
        ),
    ]
