# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-01 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0002_auto_20180731_1956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('4bf1dbb7-de2c-4a8a-aa44-7d98def6deb6'), max_length=254),
        ),
    ]
