# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-02 20:11
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_auto_20180802_1611'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Booking', '0003_auto_20180801_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking_inprogress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254)),
                ('bookingFrom', models.DateTimeField(blank=True, null=True)),
                ('bookingUntil', models.DateTimeField(blank=True, null=True)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('booking_id', models.CharField(default=uuid.UUID('a8660f61-dfdd-40dc-8837-119ca7dc5221'), max_length=254)),
                ('terraintype', models.CharField(max_length=254)),
                ('terrain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Terrain')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('905248c2-0615-45b0-838a-636a36e974b4'), max_length=254),
        ),
    ]
