# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-06 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0004_auto_20180802_1611'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('4c770da2-73ca-4edc-ab5e-d8a86171a865'), max_length=254),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('10d72422-4f66-4afe-aa49-25cf3601fbb0'), max_length=254),
        ),
    ]
