# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0006_auto_20180807_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('df796521-9fb3-4a62-b6c9-cea147566fff'), max_length=254),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='bookingFrom',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='bookingUntil',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('65a93c33-bd97-4ce0-98b4-1fd6e22f2427'), max_length=254),
        ),
    ]
