# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-07 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0007_auto_20180807_1241'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('38b8e883-c40d-4662-bcbf-db98f811e5d6'), max_length=254),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('03e71d79-5660-4664-84b4-a0026982b363'), max_length=254),
        ),
    ]
