# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-12 19:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0009_auto_20180810_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('5bf3fc33-6601-4cf3-99f7-4ade87da5844'), max_length=254),
        ),
    ]
