# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-13 22:10
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0010_auto_20180812_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('f6341e91-1c36-4025-aceb-741c9eb1eaaa'), max_length=254),
        ),
    ]
