# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 00:37
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0011_auto_20180813_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(default=uuid.UUID('ac3d16d4-b09b-43ed-b248-dc541beb6b65'), max_length=254),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
