# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-14 17:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0012_auto_20180813_2037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_inprogress',
            name='booking_id',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='booking_inprogress',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
