# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-15 19:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0014_auto_20180815_1359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking_inprogress',
            name='status',
            field=models.IntegerField(blank=True),
        ),
    ]
