# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 19:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0017_guest'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='guest',
            options={'verbose_name_plural': 'Guest'},
        ),
        migrations.RemoveField(
            model_name='guest',
            name='guest',
        ),
        migrations.AddField(
            model_name='booking_inprogress',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.Guest'),
        ),
    ]
