# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 19:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0018_auto_20180816_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='status',
            field=models.IntegerField(default=0),
        ),
    ]
