# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-16 21:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0019_guest_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking_inprogress',
            name='guest',
        ),
        migrations.AddField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking_inprogress'),
        ),
    ]
