# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-17 02:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0021_auto_20180816_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='guest',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Booking.Booking_inprogress'),
        ),
    ]
