# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0028_counter_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking_inprogress',
            old_name='counter',
            new_name='guestnumber',
        ),
    ]
