# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 18:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0029_auto_20180824_1300'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_inprogress',
            name='price',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='guest',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
