# -*- coding: utf-8 -*-
# Generated by Django 1.11.14 on 2018-08-24 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Booking', '0030_auto_20180824_1432'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking_inprogress',
            name='expiration',
            field=models.BooleanField(default=False),
        ),
    ]
